### ISSUE TITLE
Include web form in base view

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#1]
The HTML view at the base URL should contain a form to decompose DDC numbers.

**Comment by nichtich** [comment]
Started with https://github.com/gbv/coli-ana-api/commit/1705b60966be033a2b37a6b1cd9d0c7e973aeb6f.

The display could be extended by checking the member concepts at coli-conc.gbv.de/api/ to

* Add/update class labels
* Mark found concepts and link to Cocoda (e.g. bold or icons like used in Cocoda)
* Mark whether following concepts are connected by broader/narrower to each other to indicate which parts of the decomposition are part of the the class hierarchy and which parts are not

**Comment by stefandesu** [comment]
I would like to show concept details (loaded via cocoda-sdk) somewhere in the interface. Two suggestions:

1. Use an interactive popover on mouseover.
2. Show the details inline after click.

What do you prefer, @nichtich?

**Comment by nichtich** [comment]
I'd prefer popover so you can quickly scroll through the list. The concept should somehow be marked when additional information is available. Links into Cocoda could be given with icons in an additional column.

**Comment by nichtich** [comment]
As an exception: information about the full notation's class should directly be shown below the header (#5)

**Comment by stefandesu** [comment]
Sounds good. 👍

**Comment by nichtich** [comment]
Web form still can be improved but this should be discussed in issues about the specific improvements, so closing this.
