### ISSUE TITLE
Show hierarchy information

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#11]
Given a decomposition and information about member classes we can show which parts of the decomposition follow the class hierarchy, e.g.

~~~
   7----- Künste und Unterhaltung
↳ 70---- Künste
↳ 700--- Künste
↳ 700.2- Standardschlüssel für die Künste
↳ 700.2- Verschiedenes
   -0---- Facettenindikator
   --0--- Hilfstafel 1. Standardschlüssel
↳ --0.2- Verschiedenes
↳ --0.23 Das Thema als Beruf, Erwerbstätigkeit, Freizeitbeschäftigung
~~~

**Comment by nichtich** [comment]
requires #8

**Comment by stefandesu** [comment]
We could also highlight the last concept in a hierarchy as bold because it is the most specific and therefore probably the most relevant one, right?

**Comment by nichtich** [comment]
> We could also highlight the last concept in a hierarchy as bold because it is the most specific and therefore probably the most relevant one, right?

Yes, actually how it was designed at the example https://coli-conc.gbv.de/coli-ana/
