### ISSUE TITLE
Show PICA data with syntax highlighting

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#12]
Possible with [PicaEditor](https://pro4bib.github.io/pica/#/verarbeitung?id=picaeditor) or prism but it makes more sense to first discuss how results of coli-ana should become part of the K10plus catalog.

**Comment by nichtich** [comment]
Just fetch the PICA Plain data (`format=pp`) and display between analysis and list of download formats. Syntax highlighting can be added afterwards.

**Comment by stefandesu** [comment]
Only problem I see is that for PICA Plain, we need one request per notation. Maybe we could only load it when necessary? Or add some way to either
- load PICA Plain data for multiple notations, or
- include PICA data in the JSKOS result

?

**Comment by stefandesu** [comment]
> You can convert to PICA in the browser with `serializePica(picaFromDDC(jskosConcept))`.

That's even better! But where do those methods come from? They aren't used in coli-ana. 🤔

**Comment by nichtich** [comment]
I've added them in `lib/pica.js`

**Comment by stefandesu** [comment]
Now implemented (without syntax highlighting though).

**Comment by nichtich** [comment]
Syntax highlighting should be easy to implement by (re-)implementing it in a few lines of code instead of using e syntax highlighting library.
