### ISSUE TITLE
Support add table number

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#13]
[DDC add table numbers](https://ddc.typepad.com/025431/2018/04/understanding-add-table-notation-in-webdewey.html) are special classes used for number-building only. Example:

T1--0901-0905:07 Museen, Sammlungen, Ausstellungen; Sammeln von Objekten

Add table numbers are not included in German DDC available via JSKOS Server. With https://github.com/scriptotek/mc2skos/pull/71, these classes can also be converted to JSKOS.

Question: import these classes into default JSKOS Server instance or make them available in a dedicated database? These classes are not meant to be used for indexing or browsing but only for number building and decomposition. Mapping them may  still make sense for information retrieval. An additional type URI for add table numbers might help filtering.

**Comment by stefandesu** [comment]
I'd suggest to import them into the default instance. WebDewey shows these classes in the normal hierarchy, and it would be confusing to have concepts from the same concept scheme loaded from different places (I think this might not even be possible at the moment).

**Comment by nichtich** [comment]
It looks like add table numbers come in many variants so I propose iterative adding them:

* check which numbers from known decompositions are not known 
* find these numbers in MARCXML DDC dump
* adjust mapping from MARC to JSKOS to also include these number
