### ISSUE TITLE
Interface: Support passing notation via query parameter

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#16]
I'd like to put an input form at <https://coli-conc.gbv.de/coli-ana/> to start coli-ana with a DDC number.

Either redirect <https://coli-conc.gbv.de/coli-ana/app/?notation=XXX> to <https://coli-conc.gbv.de/coli-ana/app/XXX> or the other way round.

**Comment by stefandesu** [comment]
Yeah, to be honest I'm not very sure anymore why I chose that format. I vouch for using the `?notation=` syntax instead and redirect the old URLs (or simply break them).

**Comment by nichtich** [comment]
Ok, then make query URL the default and current URLs as redirect to keep existing URLs floating around in existing discussions.
