### ISSUE TITLE
Add /voc endpoint

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#2]
To return the list of supported concept schemes (only DDC by now). This can be a static JSON file until other facetted concept schemes are supported (ILC2, UDC...).

**Comment by nichtich** [comment]
Example notation could be listed in JSKOS Concept Scheme non-standard field `EXAMPLES` (also used in BARTOC and KOS-Registry but may better renamed to `exampleNotations`.

**Comment by nichtich** [comment]
Could also include 

* statistics (number of analyzed DDC numbers)
* license information

**Comment by stefandesu** [comment]
> * statistics (number of analyzed DDC numbers)

Should this go into the field `extent`? While it's not the size of the whole concept scheme in general, it is the number of analyzed notations for this particular concept scheme in coli-ana.

**Comment by nichtich** [comment]
As the whole application is focused on DDC anyway I'm not sure about the need of this endpoint anymore. To deliver statistics we could add a `/stats` endpoint instead (#29)

**Comment by stefandesu** [comment]
Yeah, I only asked about this because of the statistics. 😅 I'll close this for now! We can reopen in case we want to add support for multiple concept schemes.
