### ISSUE TITLE
Add third column?

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#38]
Details about an element of a analysis are shown on mouse over with [ConceptDetails](https://github.com/gbv/coli-ana/blob/dev/src/components/ConceptDetails.vue) but this information can likely be overlooked. Maybe add a third column with readable notation and icons linking into Cocoda and K10plus.

**Comment by nichtich** [comment]
As suggested by @stefandesu  the additional column could also be shown between analysis and label, e.g.

    --0.904-------- T1--0901-0905 Zeitabschnitte

**Comment by stefandesu** [comment]
I would suggest using https://github.com/gbv/jskos-vue for this.

**Comment by ulsw** [comment]
I don't like this - 
1st: it's doubled ... mouseover & here
2nd: if really needed: caption first!  -> Zeitabschnitte (T1--0901-0905) 

and what about the rules?

**Comment by nichtich** [comment]
I think we can argue endless, it's a usability issue that can only be solved by feedback with actual users. Everything about rules is discussed in #22 so far.

**Comment by nichtich** [comment]
> if really needed: caption first! -> Zeitabschnitte (T1--0901-0905)

done, closing this.
