### ISSUE TITLE
Replace notation-within-number-span with plain notation

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#41]
E.g. analysis of [700.90440747471](https://coli-conc.gbv.de/coli-ana/dev/?notation=700.90440747471) includes

> T1--0901-0905:074 Museen, Sammlungen, Ausstellungen; Sammeln von Objekten

which should become T1--074 instead. I marked it as bug because notation T1--0901-0905:074 does not exist in the schedules but T1--074 does. The full notation with `:` could be of use for later analysis but not needed for now and for converting to PICA.

The change can directly be done in https://github.com/gbv/coli-ana/blob/dev/lib/parseInputStream.js.

**Comment by stefandesu** [comment]
> notation T1--0901-0905:074 does not exist in the schedules

But it does, doesn't it? https://deweyde.pansoft.de/webdewey/index_11.html?recordId=int%3aT1--0901-0905%3b1%3b074

**Comment by ulsw** [comment]
stefan is right! Don't change!

**Comment by nichtich** [comment]
Well, it's an internal notation. Should we reduce to T1--074 instead only in the list of basic semantic elements as encoded in PICA?

**Comment by nichtich** [comment]
I've included the change in the conversion to PICA, so [700.90440747471](https://coli-conc.gbv.de/coli-ana/dev/?notation=700.90440747471) results in:

    045H/10 $eDDC23ger$a700.90440747471$c7$f09044$f074$g7471$Acoli-ana

which consists of DDC notations

* 2
* T1--09044
* T1--074
* T2--7471

We can close this issue but should work on bringing tabular display and PICA result more aligned (see also #42).

**Comment by stefandesu** [comment]
Now I'm confused though. What's the difference between T1--074 and T1--0901-0905:074? Why can the same number be built with both of those?

<img width="551" alt="Screen Shot 2021-07-23 at 10 17 30" src="https://user-images.githubusercontent.com/3275148/126755277-fc61a6fb-0425-4efa-8a04-f3d3ded96b5e.png">

**Comment by ulsw** [comment]
it depends on how the ddc numbers are built, 
in
709.04007479494 "T1--074" is applied, 
but in
759.030904107477595 "T1--0901-T1--0905:074" is applied

**Comment by stefandesu** [comment]
> it depends on how the ddc numbers are built

Maybe I didn't make my confusion clear. Let's keep to `700.90440747471` as an example. In my previous comment, there's a screenshot from WebDewey where it is built with "T1--0901-T1--0905:074". However, you can also build the exact same number with "T1--074":

<img width="357" alt="Screen Shot 2021-07-21 at 15 43 29" src="https://user-images.githubusercontent.com/3275148/127821414-23586830-ea60-4566-b8e9-7dd112b03007.png">

@nichtich also said "it's an internal notation." which is only more confusion. It seems like we're all talking past each other.

**Comment by nichtich** [comment]
> However, you can also build the exact same number with "T1--074"

It is possible to build the same number in different ways!

**Comment by ulsw** [comment]
> Either it is possible to build the same number in different ways

There is only *one* way to synthesize DDC numbers, e.g. cf. 

"https://www.oclc.org/content/dam/oclc/dewey/versions/print/intro.pdf
"Classifying with the DDC
5.1 ...

**Comment by nichtich** [comment]
I'm closing this issue with following solution:

* analysis uses full URIs from tables such as `T1--0901-0905:074`
* In PICA these are reduced to basic form such as `T1-074` because these are more used for retrieval

**Comment by UmaB7** [comment]
Jakob - As discussed agree with you :-)
