### ISSUE TITLE
Change markup of notation elements (bold) to align with PICA elements

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#42]
By now the show in bold the last element of a hierarchy. This information can already be seen by the hierarchy indicators at the left. Better mark bold which elements can be used to construct the full notation e.g. 700.90440747471 is build from:

    7--------------
    --0.9044-------
    ---.----074----
    ---.-------7471

Note the facet indicator not included.

**Comment by ulsw** [comment]
the 2nd "-" is free -> error!

**Comment by nichtich** [comment]
> the 2nd "-" is free -> error!

The second "-" would be filled by the facet indicator which is not included because it is no semantic element and it will not be stored in PICA.

**Comment by UmaB7** [comment]
Highlight base number in every analysis

**Comment by nichtich** [comment]
User interface and PICA field has different definition of base number.

**Comment by nichtich** [comment]
Bold elements now correspond to elements in PICA data.
