### ISSUE TITLE
Two possibilities to determine number put in $c

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#57]
Two possibilities to determine the number put in $c:

1. the longest possible DDC notation that does not share positioned digits with another notation (currently active)

2. the longest possible DDC notation in the hierarchy, based on plain string comparision

Given this example

~~~
7------- Künste und Unterhaltung (700)
70------ Künste (700)
700----- Künste (700)
700.9--- Standardschlüssel für die Künste (700.1-700.9)
700.9--- Geschichte, geografische Behandlung, Biografien der Künste #dno_syn# (700.9)
700.904- Künste--20. Jahrhundert (700.904)
-0------ Facettenindikator (0)
--0----- Hilfstafel 1. Standardschlüssel (T1--0)
--0.9--- Geschichte, geografische Behandlung, Biografien (T1--09)
--0.904- Zeitabschnitte (T1--0901-0905)
--0.904- *20. Jahrhundert, 1900–1999 (T1--0904)
--0.9044 *1940–1949 (T1--09044) 
~~~

1. $c is `7` because the next digit is also used in `-0------`
2. $c is `700.904` because all number before (`7`...`700.9`) are substrings

_Originally posted by @nichtich in https://github.com/gbv/coli-ana/issues/34#issuecomment-996648596_

**Comment by stefandesu** [comment]
Wasn't this decided to be variant 1, or is it still not clear which one we should use?

**Comment by nichtich** [comment]
This is solved but I'am sure it will come up again

**Comment by stefandesu** [comment]
Then I'll still close the issue. We can just reopen if it comes up again.
