### ISSUE TITLE
Remove everything related to the database

### ISSUE THREAD

**Issue by stefandesu** [gbv/coli-ana#69]
@nichtich Can we remove anything related to database access, or do you think it'll be necessary to use a database again in the future?

**Comment by nichtich** [comment]
I think we will use a database in the future for #29 and #36 but these will better be another kind of database. Actually I just [started with SQLite as simple cache](https://github.com/gbv/coli-ana/blob/main/k10plus/coli-ana-enrich#L31-L43) to not call coli-ana twice with same notation. For more sophisticated queries we should better experiment with Neo4J and/or Solr to include full DDC hierarchy, DDC analysis and K10plus titles indexed with DDC. In any case this will first be an independent repository that uses coli-ana as backend (and/or the reverse) but not part of coli-ana.

**Comment by stefandesu** [comment]
Alright, sounds reasonable. 👍

**Comment by stefandesu** [comment]
@nichtich Could you check the commit where I removed the database-related stuff? The only things I left were a reference in the README (with a note that the database backend is not used anymore) as well as the error type - although I added a TODO there that we should add proper error types that are used throughout the application.

In particular, there was still a reference to `GET /analyze?member=members` which I could not find in the code. Was this removed before, when we decided to remove the database backend?
