### ISSUE TITLE
Interface: support switching language of DDC labels

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#7]
We have DDC at least in German via https://coli-conc.gbv.de/api/ and in Norsk via http://data.ub.uio.no/skosmos/ddc/, so support switching between these DDC backends to select language of DDC labels. Alternatively name it "DDC source" or similar instead of language with same effect.

**Comment by nichtich** [comment]
See [at OCLC](https://www.oclc.org/en/dewey/resources/translations.html) for a list of DDC translations. Available under a CC license, at least German, Norks, [and Swedish](https://deweysearchsv.pansoft.de/webdeweysearch/).

**Comment by stefandesu** [comment]
I implemented switching of label language with Norsk as the first alternative option. Code can still be cleaned up a little bit, and we could discuss the interface. It is only a first suggestion, so please give feedback! See [Dev](https://coli-conc.gbv.de/coli-ana/dev/).

**Comment by stefandesu** [comment]
What's also missing is that the chosen language is not remembered, i.e. after a reload of the page, it will return to German as the default. I would suggest simply adding a URL parameter for this if it's a language other than the default. Much easier to implement than using local storage or cookies.

**Comment by stefandesu** [comment]
Please let me know if there are any other languages of DDC available via an API. I couldn't find any other but I'm sure they are out there.
