### ISSUE TITLE
Anzeige von GND Mappings für die zerlegten DDC Komponenten

### ISSUE THREAD

**Issue by mjanssen-gbv** [gbv/coli-ana#73]
Ziel: Bessere Nachnutzung der Zerlegung
Anwendungskontext: Digitaler Assistent, Übernahme für WinIBW, bzw. Erschließung generell

**Comment by stefandesu** [comment]
Genau das gleiche Issue hat Jakob erst gestern erstellt. ;) Siehe #72.
